### ISSUE TITLE
type mismatch in example

### ISSUE THREAD

**Issue by ub-tech** [rkdud007/alloy-merkle-tree#4]
Hi - I tried to implement the example from the ReadMe but continue to receive this error.  Any thoughts/help would be much appreciated.  Thank you.

let proof = tree.create_proof(&B256::from(U256::from(i))).unwrap();
   |                          ------------ ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `FixedBytes<32>`, found a different `FixedBytes<32>`
   
  mismatched types
`FixedBytes<32>` and `FixedBytes<32>` have similar names, but are actually distinct types
perhaps two different versions of crate `alloy_primitives` are being used?

**Comment by rkdud007** [comment]
hey first suggest to upgrade to latest version, which is synced with alloy (v0.1.1) -- binded with alloy-primitives(v0.7.6) behind. 

I suppose your project's primitive type version and alloy-merkle-tree primitive version was mismatched ( prob it was v0.7.6 vs v0.6.4 conflict -- I had experiment this recently) 

so check out for latest version of this library which is v0.6.0 and if u still have issue lmk and share me the Cargo.toml of alloy related dependencies versions.
